import type { LenderProfile, BorrowerRequest } from '@/types'

export const MOCK_LENDERS: LenderProfile[] = [
  {
    id: '1',
    userId: 'u1',
    companyName: '서울금융대부',
    description: '10년 이상의 업력을 가진 서울 기반 대부업체입니다. 개인신용대출 및 담보대출 전문이며 빠른 심사와 당일 지급이 가능합니다.',
    interestRateMin: 9.9,
    interestRateMax: 19.9,
    loanAmountMin: 1000000,
    loanAmountMax: 50000000,
    loanTypes: ['personal', 'mortgage'],
    region: ['서울', '경기', '인천'],
    plan: 'premium',
    isVerified: true,
    contactPhone: '02-1234-5678',
    contactEmail: 'info@seoulfin.co.kr',
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    userId: 'u2',
    companyName: '한국소액대출',
    description: '소액대출 전문 업체로 신용점수 무관 상담 가능합니다. 긴급 자금이 필요하신 분들을 위해 24시간 상담을 운영합니다.',
    interestRateMin: 15.0,
    interestRateMax: 24.0,
    loanAmountMin: 500000,
    loanAmountMax: 10000000,
    loanTypes: ['emergency', 'personal'],
    region: ['전국'],
    plan: 'standard',
    isVerified: true,
    contactPhone: '1588-0000',
    contactEmail: 'cs@koreasmall.co.kr',
    createdAt: '2024-02-20T00:00:00Z',
  },
  {
    id: '3',
    userId: 'u3',
    companyName: '부산담보금융',
    description: '부동산 담보대출 전문 업체입니다. 아파트, 빌라, 상가 등 다양한 담보물로 최저 금리를 제공합니다.',
    interestRateMin: 6.5,
    interestRateMax: 14.0,
    loanAmountMin: 10000000,
    loanAmountMax: 500000000,
    loanTypes: ['mortgage', 'refinance'],
    region: ['부산', '경남', '울산'],
    plan: 'premium',
    isVerified: true,
    contactPhone: '051-9876-5432',
    contactEmail: 'loan@busanmortgage.co.kr',
    createdAt: '2024-01-05T00:00:00Z',
  },
  {
    id: '4',
    userId: 'u4',
    companyName: '창업지원대부',
    description: '사업자 대출 전문. 개인사업자, 법인사업자 모두 가능하며 운전자금 및 시설자금 지원이 가능합니다.',
    interestRateMin: 8.0,
    interestRateMax: 20.0,
    loanAmountMin: 5000000,
    loanAmountMax: 200000000,
    loanTypes: ['business'],
    region: ['서울', '경기'],
    plan: 'standard',
    isVerified: false,
    contactPhone: '02-2222-3333',
    contactEmail: 'biz@startup-loan.co.kr',
    createdAt: '2024-03-10T00:00:00Z',
  },
  {
    id: '5',
    userId: 'u5',
    companyName: '대환전문대부',
    description: '고금리 대출을 저금리로 바꿔드립니다. 여러 건의 대출을 하나로 통합하는 대환대출 전문입니다.',
    interestRateMin: 10.0,
    interestRateMax: 19.0,
    loanAmountMin: 3000000,
    loanAmountMax: 100000000,
    loanTypes: ['refinance', 'personal'],
    region: ['전국'],
    plan: 'free',
    isVerified: false,
    contactPhone: '1644-7777',
    contactEmail: 'hello@refinance.co.kr',
    createdAt: '2024-04-01T00:00:00Z',
  },
  {
    id: '6',
    userId: 'u6',
    companyName: '경기신용대부',
    description: '경기도 지역 밀착형 대부업체. 지역 주민 우대 금리 제공, 방문 상담 가능합니다.',
    interestRateMin: 12.0,
    interestRateMax: 22.0,
    loanAmountMin: 1000000,
    loanAmountMax: 30000000,
    loanTypes: ['personal', 'emergency'],
    region: ['경기', '서울'],
    plan: 'standard',
    isVerified: true,
    contactPhone: '031-5555-6666',
    contactEmail: 'info@gyeonggi-credit.co.kr',
    createdAt: '2024-02-01T00:00:00Z',
  },
]

export const MOCK_REQUESTS: BorrowerRequest[] = [
  {
    id: 'r1',
    userId: 'bu1',
    title: '개인신용대출 2,000만원 급하게 필요합니다',
    description: '직장인이고 연소득 4,000만원입니다. 신용점수 720점 정도이고 급하게 2천만원이 필요합니다. 6개월~1년 상환 가능합니다.',
    desiredAmount: 20000000,
    desiredPeriodMonths: 12,
    loanType: 'personal',
    creditScore: 'good',
    region: '서울',
    status: 'active',
    viewCount: 47,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'r2',
    userId: 'bu2',
    title: '아파트 담보로 1억 대출 문의',
    description: '서울 노원구 아파트(시가 5억) 담보로 1억 대출 원합니다. 현재 은행 대출 없고 깨끗한 물건입니다.',
    desiredAmount: 100000000,
    desiredPeriodMonths: 36,
    loanType: 'mortgage',
    collateral: '서울 노원구 아파트 (시가 5억)',
    region: '서울',
    status: 'active',
    viewCount: 83,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'r3',
    userId: 'bu3',
    title: '소액 긴급대출 300만원 당일 필요',
    description: '급한 사정으로 300만원이 오늘 필요합니다. 직장인이고 다음달 상환 가능합니다.',
    desiredAmount: 3000000,
    desiredPeriodMonths: 1,
    loanType: 'emergency',
    creditScore: 'fair',
    region: '경기',
    status: 'active',
    viewCount: 29,
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'r4',
    userId: 'bu4',
    title: '카페 창업 사업자 대출 5천만원',
    description: '카페 창업을 준비 중입니다. 개인사업자 등록 완료, 점포 계약 완료 상태입니다. 시설자금 5천만원 필요합니다.',
    desiredAmount: 50000000,
    desiredPeriodMonths: 24,
    loanType: 'business',
    region: '서울',
    status: 'active',
    viewCount: 61,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
]
